language: node_js
node_js:
  - "6.0"
  - "5.11"
before_script: npm install coveralls
script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  - provider: heroku
    api_key: $heroku_api_key
